[features]
resolution = true
skip-lint = false

[programs.localnet]
survivefun = "HB3uE5XQGq1xNtW9RMSrnBegwifeLzk1xyr75ofRPrtH"

[programs.devnet]
survivefun = "HB3uE5XQGq1xNtW9RMSrnBegwifeLzk1xyr75ofRPrtH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"
